name: Build & Publish Docker image (GHCR)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# GHCR needs write permission for the GITHUB_TOKEN
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Compute a fully-lowercase image name (GHCR requirement)
      - name: Prepare image name (lowercase)
        id: prep
        run: echo "image=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.prep.outputs.image }}:latest
            ${{ steps.prep.outputs.image }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ steps.prep.outputs.image }}:buildcache
          cache-to: type=registry,ref=${{ steps.prep.outputs.image }}:buildcache,mode=max
                                                                                
  
  
  
                      
  
